### ISSUE TITLE
Handle Streams

### ISSUE THREAD

**Issue by tjchaplin** [wizicer/gulp-csvtojson#1]
The current plugin doesn't handle streams.  Ideally Gulp plugins should handle the three types of vinyl:
- Streams
- Buffers
- Empty (null) - Useful for things like rimraf, clean, where contents is not needed.

https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md

**Comment by tjchaplin** [comment]
The pull request has updated tests, and should properly handle streams now.

Would this be ok to merge in?  Do you want to discuss further?

**Comment by wizicer** [comment]
Wonderful work, you almost rewrite the whole code base, I'll look into it ASAP.

BTW: I just observed one unit test failed in your PR.

**Comment by tjchaplin** [comment]
Please let me know.  All unit tests passed on my side.  I have also upgraded the packages, so make sure to do an npm install before npm test.

**Comment by wizicer** [comment]
Finally, I changed `replace(/\s\n/g,'')` to `replace(/\s?\n/g,'')` to make it work, my test bed is linux which only generate `\n`.

**Comment by wizicer** [comment]
code merged, so close this issue.
