### ISSUE TITLE
Remove option to create JS file

### ISSUE THREAD

**Issue by tjchaplin** [wizicer/gulp-csvtojson#3]
Further reviewing the code...it seems like there are too many paths for the plugin.  Ideally there should be a single purpose; i.e. stream `csvtojson` module using gulp.  The current plugin is streaming, but also will create a js file depending on options.  The creation of a JS file could(should) be done in a different plugin.  Here is the gulp plugin guidelines which provides a little more detail: [Gulp Plugin Guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md)

I will open up another issue to discuss further.

Here is what currently exists:

``` javascript
var gulp = require('gulp');
var csvtojson = require('gulp-csvtojson');

gulp.task('default', function () {
    return gulp.src('src/file.csv')
        .pipe(csvtojson())
        .pipe(gulp.dest('dist'));
});
```

I think this should be:

``` javascript
var gulp = require('gulp');
var csvtojson = require('gulp-csvtojson');
var insert = require('gulp-insert'); //module to insert into streamed data


gulp.task('default', function () {
    return gulp.src('src/file.csv')
        .pipe(csvtojson())
        .pipe(insert.prepend('var anyVariable = '))
        .pipe(insert.append(';'))
        .pipe(gulp.dest('dist'));
});
```

[Gulp Insert plugin](https://github.com/rschmukler/gulp-insert)

**Comment by wizicer** [comment]
Good suggestion, I agree with you, this is better than the redundant option. 

To assist the consumer who also may have such type of requirement, we can write them as standard usage in README.

**Comment by wizicer** [comment]
I tried remove option and created PR #4, please take a look, and let me know your suggestion or concern.

**Comment by wizicer** [comment]
#4 has been merged, thus close this issue.
